@profile-url=http://localhost:5047
@id={{$guid}}

### POST SocialProfileDetails
# @name postProfileDetails
POST {{profile-url}}/profile
Content-Type: application/json

{
    "id" : "{{id}}",
    "name": "Dapr",
    "discord": "https://bit.ly/dapr-discord",
    "bluesky": "https://bsky.app/profile/daprdev.bsky.social",
    "linkedin": "https://www.linkedin.com/company/daprdev"
}

### GET SocialProfileDetails
@get-url=http://{{postProfileDetails.response.headers.Location}}
GET {{get-url}}