apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: mystatestore
spec:
  type: state.postgresql
  version: v2
  metadata:
    - name: connectionString
      value: "postgres://postgres:postgres123@localhost:5432/"
